### PR TITLE
Issue #572 - Move SDR documentation to SDR repo

### LINKED ISSUE #572: Documentation📄: Move the SDR docs into the SDR directory
### What is the current documentation state?

We have decided to sunset the OH Documentation for SDR.  See discussion over in:
https://github.com/open-horizon/open-horizon.github.io/issues/358

Before we delete the markdown, I propose that we move those doc files into the SDR directory:
https://github.com/open-horizon/examples/tree/master/edge/services/sdr

### Where is this stated?

_No response_

### Why do you want to improve the statement?

_No response_

### Proposed Statement

_No response_

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by johnwalicki**
Signed-off-by: John Walicki <johnwalicki@gmail.com>

This PR fixes #572 

Add the SDR doc and diagram to the example SDR directory as  first step of sunsetting the SDR docs from the Open Horizon Documentation website.

### CODE REVIEW

**Comment by t-fine** [comment]
@johnwalicki hm, do you think these files would fit better in the `edge/evtstreams/sdr2evtstreams` directory? That is more of the "top level application" of the SDR service. Or maybe a few key files could just be duplicated?

**Comment by johnwalicki** [comment]
@t-fine Possibly,  I don't have an opinion. I've never implemented this service.  My goal was to preserve the documentation / image files and kill off the OH SDR docs.

Where do you recommend?

**Comment by t-fine** [comment]
@johnwalicki alright yeah then if you don't mind moving them over to `edge/evtstreams/sdr2evtstreams` that would be awesome

**Comment by johnwalicki** [comment]
@t-fine I've pushed another commit into this PR which moves the SDR architecture diagrams to the `edge/evtstreams/sdrevtstreams` directory.

Please review / approve if appropriate.

**Review by t-fine — APPROVED** [review]

**Comment by t-fine** [comment]
@johnwalicki this looks good to me! I'll go ahead and merge. Sorry for the delay

**Pull request merged**
