### PR TITLE
Dependency tree fixed

### PR DESCRIPTION
**Pull request by deprov447**
Updated some of the dependencies manually to fix dependency tree error. Able to run `npm update` now.
Resolves issue #506 

Signed-off-by: Anubhav Choudhary <ac.10edu@gmail.com>

### CODE REVIEW

**Comment by deprov447** [comment]
Also, [`apollo-upload-server`](https://github.com/open-horizon/examples/blob/3e5ff07aef3c17eab96e8ad975de5489551004f1/cloud/sdr/ui/sdr-app/package.json#L26) is long [deprecated](https://www.npmjs.com/package/apollo-upload-server) and the replacement [`graphql-upload`](https://www.npmjs.com/package/graphql-upload) can be used in place. But this requires some source code changes also (so maybe a different ticket?)

**Review by clementkng — COMMENTED** [review]
Thanks for looking into this! As someone who's not too familiar with resolving these issues, could I ask which `npm` version are you using and how were you able to determine which packages needed to be updated?

**Comment by deprov447** [comment]
I am using npm version: `8.4.0`. `npm update` gave me a `ERRESOLVE` error with hint on which dependencies are in conflict. IIRC I had to remove whatever version these deps were and manually install them again.

**Comment by t-fine** [comment]
Closing this since we archived the cloud/sdr infrastructure code

**Pull request closed without merging**
