### PR TITLE
bug: 556 new base image to build arm64 cpu_percent docker container

### PR DESCRIPTION
**Pull request by t-fine**

### CODE REVIEW

**Review by johnwalicki — APPROVED** [review]
Glad we are migrating to the ubi9 base image.  Approved

**Comment by johnwalicki** [comment]
I found an easier way to fix this issue.  See #560 and #561

While I like using ubi9 images, I also like how small the alpine images are.  Using the technique describe in #560, I was able to build the arm/arm64/amd64 cpu_percent containers successfully using `alpine:latest`

These alpine container images are tiny compared to the ubi9 implementations.
```
localhost/openhorizon/ibm.cpu_arm64         1.2.6      a51123e8c8c5  2 minutes ago  10.4 MB
localhost/openhorizon/ibm.cpu_arm           1.2.6      1cd9e27e4dc8  2 minutes ago  7.74 MB
localhost/openhorizon/ibm.cpu_amd64         1.2.6      fb5f7f547ddc  2 minutes ago  10.7 MB
```

**Comment by johnwalicki** [comment]
I suggest we close this PR and open a new PR using the technique described in #560

**Comment by t-fine** [comment]
Addressed with different PR.

**Pull request closed without merging**
